apiVersion: v1

kind: Service

metadata:

  name: helloworld-service

spec:

  selector:

    app: helloworld

  ports:

    - name: https

      protocol: TCP

      port: 443

      targetPort: 8080
