---

- name: Install Python
  apt:
    name:
    - python-apt
    - python3-apt
    state: latest
  become: yes

- name: Install pip3
  apt:
    name: python3-pip
    state: present
    update_cache: yes
  become: yes

- name: Install virtualenv via pip
  pip:
    name: virtualenv
    executable: pip3
  become: yes
  become_user: root



# Install system apt packages

- name: update cache
  apt: name=python-software-properties state=present update_cache=yes cache_valid_time=43200
  become: yes

# - name: disable lighttpd
#   systemd: name=lighttpd state=stopped enabled=no  # To avoid conflicts with nginx
#   become: yes

- name: install packages
  apt: name={{item}} state=latest
  loop:
    - tree         # Optional
    - python-pip   # Optional
    - python-dev   # Optional
    - python3-pip
    - python3-dev
    - nginx
  become: yes

# Install the app, note: don't do these tasks with become sudo

- name: clone repo
  git:
    repo: 'https://github.com/{{ github_user }}/{{ app_name }}.git'
    dest: /home/{{ ansible_ssh_user }}/{{ app_name }}
    update: yes  # Does a git pull if the repo already exists

- name: install modules in a virtualenv
  pip:
    requirements: /home/{{ ansible_ssh_user }}/{{ app_name }}/provisioning/requirements.txt
    virtualenv: /home/{{ ansible_ssh_user }}/{{ app_name }}/env
    virtualenv_python: python3.5
  tags:
    - venv

  
